{{- range .Values.targetGroups }}
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  serviceRef:
    name: {{ .serviceRef.name }}
    port: {{ .serviceRef.port }}
  targetGroupARN: {{ .targetGroupARN }}
{{- end }}
